name: Deploy Static Website to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Upload to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name myk \
            --account-key "${{ secrets.AZURE_STORAGE_KEY }}" \
            --destination '$web' \
            --source result-app \
            --overwrite
